### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by QDelobel** [TinkerTools/poltype2#12] opened 2022-07-01 15:04 UTC
Hello,

I'm a doctorate student who tries to parametrize one ligand using your software but I'm currently running into a wall about a problem that seems to be memory allocation :
MemoryError: std::bad_alloc

I'm attaching the files generated after the test if you had some time to help me resolve this issue.
[Poltype-FBP.zip](https://github.com/TinkerTools/poltype2/files/9029827/Poltype-FBP.zip)

Thank you for your attention.

**Comment by bdw2292** [comment] 2022-07-01 15:16
Hey,

Is this submission on some cluster where you can specify memory resource requirements? Or is there a way to check available, ram and scratch space? One thing to try is to remove the keywords in input file that are controlling the memory resources. I try to have reasonable defaults so nobody has to deal with that. The larger resources available on the node its running computations on, the more default resources are allocated to the QM jobs. Another thing just to be careful about, is the input is PDB, thats okay sometimes. However, since there isnt explicit bond order in the PDB file, openbabel will "guess" what it thinks the bond order should be. In some cases that will make something you might not want, so just safer to use a file with bond order explicit. I also notice there are no hydrogens on the sugar oxygens (not sure which protonation state you are going for). Im running on our cluster to see if QM still crash, its using PCM by default since there are phosphate groups (highly charged) and sometimes hydrogens can transfer with just gas phase QM geometry optimization.

**Comment by QDelobel** [comment] 2022-07-01 15:25
Yes, i run it on a cluster so that's why i specified the number of core and maximum memory used because when I didn't it launched itself with the totality of the ressource of the core (12 CPUs and 52GB) with could be harmful for other jobs. For scratch space, I don't think it should be a problem.

**Comment by bdw2292** [comment] 2022-07-01 15:27
Okay I will let you know if and when the QM converges.

**Comment by bdw2292** [comment] 2022-07-05 15:52
I added hydrogens to sugar and optimization converges fine. I think a charge of -7 makes things particularly difficult, psi4 geometric,optking and even gaussian optimizers all failed...

**Comment by QDelobel** [comment] 2022-07-06 07:11
Hello,
Yes it did the same for me, psi4 terminated normally at first with the optimization complete but then an error came out on my output file and my poltype.log generate from the cluster in which i do the calcul about some sort of Value error because of 'bond created after optimization' or 'too many bad steps'. I even tried with a SDF file of my ligand and it did the same errors.
[output-poltype.zip](https://github.com/TinkerTools/poltype2/files/9052450/output-poltype.zip)
e

**Comment by QDelobel** [comment] 2022-07-08 15:27
I also did try with another ligand (OXL) and this time it was not an error of Bond (like for the FBP) but it seemed to be missing Vdw in QM or convergence issue.
So it doesn't seem like it was a problem of separate folder for my first ligand FBP.
[FBP.zip](https://github.com/TinkerTools/poltype2/files/9072031/FBP.zip)
[OXL.zip](https://github.com/TinkerTools/poltype2/files/9072032/OXL.zip)

**Comment by bdw2292** [comment] 2022-07-08 15:30
https://utexas.box.com/s/7udhp6qrai3ihslg1vsx86vgg8usffic
here is FBP, I dont understand what is the issue when you were running I can look at input files. Just adding hydrogens to sugar.

**Comment by bdw2292** [comment] 2022-07-08 15:36
Okay the input sdf file still doesnt have hydrogens attachted to the sugar (which crash for me too). Its very highly charged and will cause problems.

**Comment by QDelobel** [comment] 2022-07-08 15:40
Oh, i see.
I'm a little new to the dynamic subject and parametrization ,my phd is in in codirection cancerology-virology and dynamic and I studied more on biology and virus. So just a naive question but how exaclty did you specify the coordinates to add the hydrogens on the sugar ?

**Comment by bdw2292** [comment] 2022-07-08 15:44
From the other one, my guess by reading error in qm log files is the new geomeTRIC optimzation engine doesnt play well with PCM in psi4. The newer commit has a "try new qm opt algorithm but if fail try old psi4 default". Ill see if that works.

Ah okay, there are lots of ways to add but I like to open the SDF file in pymol and just click on each oxygen atom you want to add, then on right hand side click add hydrogens.

**Comment by bdw2292** [comment] 2022-07-08 15:47
Okay I was right, it finished in minute cause molecule is so small

**Comment by bdw2292** [comment] 2022-07-08 17:03
You can run with a new commit and that should fix issue with PCM failing on psi4's new optimizer we added.

**Comment by QDelobel** [comment] 2022-07-11 07:29
Ok thnak you, how do I procede to run with this new commit for my second small ligand ?

**Comment by QDelobel** [comment] 2022-07-11 10:06
I also did try to run my FBP ligand like the one that you did that finished but I had an error on the poltype.log about some segmentation fault if you had an idea what the problem could b
[FBP.zip](https://github.com/TinkerTools/poltype2/files/9082940/FBP.zip)
e

**Comment by bdw2292** [comment] 2022-07-11 21:56
This happens sometimes when not enough memory. Can also try just rerunning again to see if its reproducible (since I know it completed for me).

**Comment by QDelobel** [comment] 2022-07-12 07:23
Just for information, how much memory did you use ?

**Comment by bdw2292** [comment] 2022-07-12 13:56
Can we do a simpler test on like a water molecule. This can rule out issues like conda installation. Also might be issue with scratch space writing (not enough space or where trying to write doesn’t have right permissions etc). If that works then whatever resources input you used to try, try doubling everything etc…

**Comment by QDelobel** [comment] 2022-07-12 14:43
I tried to use the same water sdf than the one in the example file but it sent me 2 minutes after executing poltype a termination signal in poledit.x like this in the poltype.log
[Water.zip](https://github.com/TinkerTools/poltype2/files/9094090/Water.zip)


While I'm currently relaunching my OXL ligand more small
[3srd_E_OXL.sdf.zip](https://github.com/TinkerTools/poltype2/files/9094047/3srd_E_OXL.sdf.zip)

but it continues since hours so I don't know what happened with water

**Comment by bdw2292** [comment] 2022-07-12 14:50
Seems like it may be some tinker installation issue.

I copied the poledit command in poltype.log file and replaced the prm file with the one in my filesystem (poledit 1 water_3D.gdmaout /home/bdw2292/poltype2/ParameterFiles/amoebabio18_header.prm < water_3D-peditin.txt) then it works fine. Can you run some other tinker programs? Im guessing analyze at least works because that is used for checking tinker version at beginning of poltype.

**Comment by bdw2292** [comment] 2022-07-12 14:51
For your other molecule, just be careful about hydrogens. Where did the SDF file come from?

**Comment by QDelobel** [comment] 2022-07-12 14:51
I did analyze and poledit.x and it seems to work for these two 
![image](https://user-images.githubusercontent.com/108536286/178519474-5b43e1ad-5530-4b20-9665-783995c20ee3.png)

**Comment by bdw2292** [comment] 2022-07-12 14:59
Can you try copying the poledit command from poltype log file and run that manually in your terminal?

Okay, I guess if they dont have information about which protonation state it should be in you can try using https://docs.chemaxon.com/display/docs/pka-plugin.md . Also poltype uses a paper from the Durrant-Lab for ionization state prediction at pH~7. I think the results are comparable to chemaxon (but havent tested large scale). The paper (dimorphite-DL) has more details about accuracy.

**Comment by QDelobel** [comment] 2022-07-12 15:11
Ah i see where is the problem,
when I launch the test in my cluster, it takes a nodes free but the one chosen for the test of water show an error with all the commands. But I wouldn't know exaclty why.

**Comment by QDelobel** [comment] 2022-07-12 15:22
Ah and for the pKa plugin in chemaxon do you have some information to use/download it to see more precisely the state of my ligands ?

**Comment by bdw2292** [comment] 2022-07-12 15:28
I think it may require a chemaxon license, there is some documentation on how to use pka plugin. Alternatively, poltype outputs IonizationState files when running on any molecule. What you have may be correct for carboxlic acid (there are two of them). If pka is 5 and ph is 7 then I guess should be deprotonated.

**Comment by QDelobel** [comment] 2022-07-20 08:11
Hello,
I did continue to test poltype with more memory but I encountered an issue in the poltype.log file where it seems to run indefinitely some sort of displacement. If you have some time do you have any idea where could the problem be since it did work normally for water (last message) ?

[SO4-Test.zip](https://github.com/TinkerTools/poltype2/files/9147831/SO4-Test.zip)

I am also trying to do my bigger ligand FBP (with the hydrogens like you said) but it seems to follow the same path but slower since its more big (it's not finished so maybe it will be good)

![image](https://user-images.githubusercontent.com/108536286/179931116-c19f2825-37f9-4ab2-9cfa-4871114431e9.png)

Thank you for your answer

**Comment by bdw2292** [comment] 2022-07-20 14:53
Hello,

So for the displacements this is an output from Psi4s PCM optimizer (for geometry optimization) that gets piped to stdout (which I pipe to poltype.log). Just be careful about input protonation state, I kinda quickly only added hydrogens to your sugar for testing (but the carbons still didnt have hydrogens added), so you can see in the log file the hydrogens on some of your carbons were added automatically! Previously I only add automatically for carbons missing one hydrogen but with new commit now it will also add hydrogens to carbons missing two bonds (or valence <4). Although the protonation state issue may be independent of any psi4 problems. PCM optimizer in psi4 by default (used when we have concentrated charge like phosphate in your molecule to prevent hydrogens from jumping around to other atoms) is not super great and apparently isnt compatible with our new geomETRIC psi4 optimizer. As for the sulfate you sent me mine finished fine, maybe not enough memory inputs? The program ended up using 20 GB of RAM and 8 threads by default.

**Comment by QDelobel** [comment] 2022-07-21 07:54
Hello, thank you for your answers, so I did run with a FBP with all missing hydrogens but it did have an error in the poltype.log ( about missing option it seemed ?), here are the files generated and just a screen capture of the error at the end

[FBP.zip](https://github.com/TinkerTools/poltype2/files/9157349/FBP.zip)


![image](https://user-images.githubusercontent.com/108536286/180159658-8f80d4af-2e1e-495c-b809-6908491af08d.png)

If you have some insight about this error, thank you for your time

**Comment by bdw2292** [comment] 2022-07-21 13:37
How much scratch space do you have available on your submission node?

**Comment by QDelobel** [comment] 2022-07-21 13:47
I have 3,6Tb of available on the node where this calcul was done
![image](https://user-images.githubusercontent.com/108536286/180229425-7a0d7488-4f52-4741-9273-11d48f950e35.png)

**Comment by bdw2292** [comment] 2022-07-21 15:00
Here is the SO4 finished https://utexas.box.com/s/wlkxm2cokharx7hnwas7ja0rru2xbdj4

I guess one thing to try is resubmit psi4 command manually in your terminal and try to reproduce issue. I am running on our cluster. There are other things to try playing with like lowering basis set/increasing input resources etc (only for testing/debugging we want default settings for actual parameter derivation).

**Comment by bdw2292** [comment] 2022-07-21 15:58
Here is everything up to electrostatic potential fitting step  for the molecule with two phosphates and sugar (it finished the QM there on my end). https://utexas.box.com/s/yqalmsmnxupm04mwibwm32lgyjhzcxpq

**Comment by QDelobel** [comment] 2022-07-21 19:16
Thank you for your logs on your side, i did find that mine finished suddenly after genreating the grid with the error showed on my New-esp.log file (from my FBP.zip of the last message) and the only difference I did see was on the memory so I will try with more in regards to my available ressource.

**Comment by bdw2292** [comment] 2022-07-25 17:34
Glad it worked out. Your torsion profile plots look very reasonable (see OPENME) folder. Just let me know if the instructions on the readme page make/dont make sense. Just want red curve (amoeba) to match blue curve (QM)
(https://github.com/TinkerTools/poltype2/blob/master/README/README_OUTPUT.MD#openme-plots) accessed by hyperlink from main readme file (README.MD).

**Comment by QDelobel** [comment] 2022-07-26 07:54
Hi,
Thanks for your help,

for now most of my test are finishing so it seemed to have been resolved (and my curves are matching well) but I had a test with this small ligand that didn't finished and the cause seem to be from missing QM SP energy value for torsion during QM optimization.
Could it be possible for you to test on your side if you obtained the same error as me and if you have any idea what is causing this error ?

[OXL-failed.zip](https://github.com/TinkerTools/poltype2/files/9187737/OXL-failed.zip)

**Comment by bdw2292** [comment] 2022-07-26 13:49
No problem. This is one you already sent me, im not sure what went wrong with psi4 on your end. Can try manually reproducing by copying command in log file and pasting in terminal as a start. Here is latest.

https://utexas.box.com/s/nol9cvm558er03c4fs5ct3hgp1rbqpld

**Comment by bdw2292** [comment] 2022-07-26 15:27
Yes sorry that is the command I meant. Do you mean where it asks for displacements? Its in the qm optimization log files ( see below). The psi4 version is "psi4                      1.6.1+5b9f6e3    py39h1bd450f_0    psi4"
     ----------------------------------------------------------
                                   FINDIF
                     R. A. King and Jonathon Misiewicz
         ----------------------------------------------------------

  Using finite-differences of energies to determine gradients.
    Generating geometries for use with 3-point formula.
    Displacement size will be 5.00e-03.
    Number of atoms is 6.
    Number of symmetric SALCs is 12.
    Translations projected? 1. Rotations projected? 1.
    Number of geometries (including reference) is 25.
 25 displacements needed ...

  //>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>//
  //    FiniteDifference Computations  //
  //<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<//

**Comment by bdw2292** [comment] 2022-07-26 15:39
Possibly, let me know if that one works then I will "freeze" the psi4 package on our yml file if that turns out to be the case.

**Comment by QDelobel** [comment] 2022-07-27 08:38
Hello,
So i did retry the test and it still blocked at the qm optimization step but what I found is that some of my ligand did pass this QM optimization (like FBP/PYR or GOL) but those with no hydrogen and some high charge like SO4 and OXL (i even used pymol but no hydrogen was need for those small ions) didn't passed it and try indefinitely or crashed after that step, right now my PO4 ion is in the same state where its currently trying to optimize but doesn't seem to work.

I did sent all the file for each ligand i talked about so maybe its not the psi4 version but just these small molecule that are the problem ?
https://drive.google.com/drive/folders/1izO-RJlWv0y931ACmbkoiS4jY4o8QnN8?usp=sharing

**Comment by QDelobel** [comment] 2022-07-27 11:40
I also have a question after i finalized the parametrization of this ligand FBP,  I need to transform my pdb structure to xyz format with tinker but how could I use this key generated to my force field parameters file. And also I have this same ligand 4 times on my structures, should I used poltype for all 4 or normally it should work with one since they all have the same binding site ?

**Comment by bdw2292** [comment] 2022-07-27 13:51
At least for the cases where psi4 works for me but not on the other end it’s definitely psi4 issue (input mem resources or version etc..). The rule of thumb though is if it’s highly charged and we use PCM (to prevent any hydrogens from moving) then psi4 optimization algorithm will take longer and might have more convergence issues. With last commit if enough psi4 torsion optimizations fail it tries with Xtb (which doesn’t have pcm feature etc, so idk if we will run into case where hydrogens move or not yet). 

For generating the tinker xyz, the main thing is we have a tool called pdbxyz that works by recognizing pdb topology and mapping to type number in prm file. Pdbxyz doesn’t recognize ligand topology and so doesn’t know how to map ligand atom index in pdb to type in ligand xyz file. If the atom order of ligand in xyz and pdb are the same then this is much simpler to manually go through your xyz made from using pdbxyz and add correct ligand types yourself. If not then need some topology/smiles matching. Poltype can do this for you (see example on main page where input complex ligand and protein pdb is given). Just need to also give ligandxyzfilenamelist and keyfilenamelist as inputs also. You can add an additional keyword “boxonly” to quit program after making boxes. I can add another one like “xyzonly” to quit after making the tinker xyz file with protein and ligands complexed.

**Comment by QDelobel** [comment] 2022-07-27 14:03
Thank you for all those informations, maybe i will try to get the last commit when some of my current parametrization that are working are complete.
So for poltype to do the protein-ligand xyz for me i would need to create a new poltype.ini with these parameters :

uncomplexedproteinpdbname='name'.pdb
complexedproteinpdbname='name'.pdb 
binding
keyfilenamelist=FBP.key
ligandxyzfilenamelist=FBP.xyz

and just run the same poltype command line if I understood correctly ? 

Also yes for my case it would be interesting to quit after the tinker xyz file with prot-ligand is formed if it's not too much work ?

**Comment by bdw2292** [comment] 2022-07-27 14:49
Im going to try my best to get it working with psi4 first (if I can get example that fails). Sometimes optking pcm fails for me too. Trying to "loosen convergence criteria" for pcm. Also since some of your systems have no hydrogen im turning pcm off.

Yeah thats pretty close, so just two things "uncomplexedproteinpdbname" is only used for pdb2pqr to determine protonation state (I keep it in seperate example box). Then since you have 4 ligands, you want something like "keyfilenamelist=FBP1.key , FBP2.key , FBP3.key , FBP4.key" and "xyzfilenamelist=FBP1.xyz , FBP2.xyz , FBP3.xyz, FBP4.xyz". I will update that example to have comma separated list (current example only has one item in list).

**Comment by QDelobel** [comment] 2022-07-27 14:57
Ok, just a naive question but since my four ligands are the same molecule in each of the monomer in the tetrameric structure, should I only need to copy-paste the same key/xyz or I need to run poltype for each of the four ?

**Comment by QDelobel** [comment] 2022-07-27 15:21
I just did a first test and here is the error message with the files generated if you have an idea of the problem
![image](https://user-images.githubusercontent.com/108536286/181285030-ffe94e0c-af57-4df1-8e29-0c934934e76b.png)
[Test-binding.zip](https://github.com/TinkerTools/poltype2/files/9200434/Test-binding.zip)

**Comment by bdw2292** [comment] 2022-07-27 18:36
Okay so the new commit should be more robust with pcm, I loosened convergence tolerance with psi4 in this case and turn off pcm when hydrogens are not in molecule.

For making the tinker xyz, just make sure the inputs look something like below. The error you saw was because the FBP molecule in your pdb is completely unprotonated but your parameterized molecule input FBP1.xyz … is protonated. So poltype is trying to match with smiles strings to PDB but it will fail since the topology is not the same. I have added an error when this occurs now saying “ValueError:  ligandsmiles not matching anything in PDB! [H]~[#8]~[#15](~[#8]~[#6](~[H])(~[H])~[#6]1(~[H])~[#6](~[H])(~[#6](~[H])(~[#6](~[#6](~[H])(~[H])~[#8]~[#15](~[#8])(~[#8]~[H])~[#8]~[H])(~[#8]~[H])~[#8]~1)~[#8]~[H])~[#8]~[H])(~[#8])~[#8]~[H]” etc. I also just added the keyword “makexyzonly” if you want to terminate program after making xyz. You can add hydrogens using “builder” in pymol, so for example on the terminal oxygens, make sure the formal charge assigned is 0, then that tells pymol it can add hydrogen (if its -1 then it thinks it cant add hydrogen). 

If you want to also include the other molecules (I assume for buffer or something etc). Will need to include them as well in “ligandxyzfilenamelist”. However, if you want to do binding free energy and disappear only the FBP molecules, now also need to specify another keyword “annihilateligandxyzfilenamelist= FBP1.xyz , FBP2.xyz , FBP3.xyz , FBP4.xyz” so the program knows “which ligands” to disappear electrostatics/vdw. If you don’t include those other ligands in the ligandxyzfilenamelist keyword, then when making the tinker XYZ, the program will ignore it (no smiles string detection). Then for waters/ions within I believe 8 angstroms of any ligand those will be included in tinker xyz file as well. There was a few bug fixes, some mine (too many special cases…) and one where babel was generating wrong pdb and converting MET to ALA!! when I remove some of the HETATMS, so replaced with my own parser. Also a few protein residues are missing (in the beginning of PDB), some missing atoms were added as well (not in missing residues though). 

complexedproteinpdbname=3srd-ph7,5.pdb
binding
keyfilenamelist=FBP1.key , FBP2.key , FBP3.key , FBP4.key
ligandxyzfilenamelist=FBP1.xyz , FBP2.xyz , FBP3.xyz , FBP4.xyz
makexyzonly

**Comment by QDelobel** [comment] 2022-07-27 19:02
Alright, thank you so much for all the help, i will looking into it a little bit tonight and test everything tomorrow.

**Comment by QDelobel** [comment] 2022-07-27 19:46
Ah right now I discovered something that when i did last time the protonation in PyMOL for Poltype Parametrization I did it from the sdf file from one FBP (https://www.rcsb.org/structure/3srd, in instance coordinates) and it gave me a 34 atoms molecules.

But when I did it right now when using my whole protein (obtained on the same link) and selecting each FBP in PyMOL and protonate it with hydrogens I only obtained 32 atoms for each FBP, will it be a problem for the program since there is a difference of 2 hydrogens ?

**Comment by bdw2292** [comment] 2022-07-27 20:10
So the issue is how each program reads or guesses the formal charge of the atom. Im guessing its one of the terminal oxygens that is missing H (one on both sides of phosphate). This happened to me aswell, if in original PDB file, the formal charge is -1, then if you select the whole molecule in pymol and try to add H it wont add to that O atom with -1 formal charge. So one way to fix is to change the input PDB file (charge field). The other way is to use pymol builder to tell it the formal charge is 0, then when you ask pymol to add hydrogens it sees empty valence and can fill with hydrogen for you. Just need to change from whole molecule atom selection to atom selection, then when you click on atom you want to change there is builder button on top right to modify charge etc... I also just fix another bug where babel thinks ions can have bond if they are too close to other atoms...

**Comment by pren** [comment] 2022-07-27 20:13
For small molecules, use Marvin (chemaxon) to evaluate pKa and possibility of multiple protonation states.

**Comment by bdw2292** [comment] 2022-07-27 20:37
Alternatively you may just use poltype to print out the relevant states. The only difference is that with the software im wrapping it doesnt give probability estimate, but the 4 states generated are the four dominant states in marvin sketch (well one of them only has ~ 4% chance in relevant pH range according to marvin.., the one with one H on both phosphates). 
"structure=FBP.xyz
genprotstatesonly
"

**Comment by QDelobel** [comment] 2022-07-27 20:50
I see, on my side i did resolve this difference of two hydrogen with your advices on pymol.

I will test the binding with my pdb tomorrow and will also look at these probability of dominant state, it could be interesting in the case of this ligand since its considered an allosteric regulation on this site on my protein so it could always be good to see the different states of protonation.

**Comment by QDelobel** [comment] 2022-07-28 12:35
Hello,
it progressed well for the binding but there was some missing residues on my input pdb so i'm installing modeller like said in poltype protein preparation.

**Comment by bdw2292** [comment] 2022-07-28 13:52
Glad to hear it. If I recall they should license via email right away.

**Comment by QDelobel** [comment] 2022-07-28 15:33
I just have accessed to modeller and tried it on my cluster with the .ini here 
`pdbcode=3srd
numproc=8
maxdisk=200GB
maxmem=50GB
coresperjob=1`
but it returned this error on my output : 
![image](https://user-images.githubusercontent.com/108536286/181577868-5cd29385-3495-45a1-8a9a-e480fe2e01c6.png)

And here are all the files generated, if you have time to look.It seemed to have found my structure but found some sort of error on it ?
[Test-modeller.zip](https://github.com/TinkerTools/poltype2/files/9212137/Test-modeller.zip)

**Comment by bdw2292** [comment] 2022-07-28 18:08
Thanks for catching that, this represents a more "general" case as to what I cooked up for the previous PDB I tried this on. The two main issues is that you can have repeating residue numbers between different chains (where as sometimes in PDB resnum keeps going across all chains I believe). Another issue is how the "seq" file generated from Modeller behaved a bit differently from what I saw last time, the PBD file has chains A-D but not all sequential but each line in seq file generated from modeller using the crystal pdb as input doesnt correspond to segments of each chain (like I would expect A-segment first line, then like B-segment ,. ...) anyway its not a problem if program can keep track of chain and residue number concurrently, I will come back to this.

**Comment by bdw2292** [comment] 2022-07-29 22:00
Should be fixed now

**Comment by QDelobel** [comment] 2022-07-30 17:44
Hello,
 it finished correclty but is it normal if the pdb generated doesn't have the atoms for the different ligands. For example here is the pdb when downloaded from the website (with missing residues) :
[3srd.zip](https://github.com/TinkerTools/poltype2/files/9227021/3srd.zip)


and here is the files from poltype (this one with all the residues but missing the ligands like FBP) : 
[Test-missing.zip](https://github.com/TinkerTools/poltype2/files/9227017/Test-missing.zip)

**Comment by bdw2292** [comment] 2022-07-30 17:55
Glad to hear it, yes Modeller just adds missing residues and minimizes the structure. If you want to add ligands manually afterwords can try pymol or VMD etc...

**Comment by bdw2292** [comment] 2022-08-02 17:53
On second thought, this is a non trivial issue with many ligands and a common issue... so I added a feature to handle this. See input file below. Output file will have _align.pdb in name.

complexedproteinpdbname=pdb3srd.pdb
uncomplexedproteinpdbname=3srd_filled.BL00020001_final.pdb

**Closed** 2022-10-05 14:21 UTC
